auto: true
server: true
permalink: /blog/:title
baseurl: http://firegento.com
name: FireGento Blog
description: FireGento Blog
url: http://firegento.com
exclude:
- .gitignore
- README.md
paginate: 5
paginate_path: "blog/page:num"
